version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
