[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "12"

[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
    # cache for one month
    cache-control = "public, max-age=2592000"

[[plugins]]
  package = "netlify-plugin-checklinks"