[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "14"

  # cache Cypress binary in local "node_modules" folder so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
    # cache for one month
    cache-control = "public, max-age=2592000"

[[plugins]]
  package = "netlify-plugin-cypress"