[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "14"

  # cache Cypress binary in local "node_modules" folder so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
    # cache for one month
    cache-control = "public, max-age=2592000"

[[plugins]]
  package = "netlify-plugin-cypress"

[[plugins]]
  package = "netlify-plugin-no-more-404"

  [plugins.inputs]
  # either "warn" or "error"
  on404 = "error"
  cacheKey = "no-more-404"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = ""

  [[plugins.inputs.audits]]
    path = "/blog/2020/markdown-capabilities-in-eleventy/"

  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    # pwa = 0.9