[dev]
framework = "#custom"
command = "npx @11ty/eleventy --watch --serve --quiet --port 2000"
port = 2020
targetPort = 2000
autoLaunch = false

[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
  # cache Cypress binary in local "node_modules" folder so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
    # cache for one month
    cache-control = "public, max-age=2592000"

[[headers]]
  for = "/css/giscus-custom.css"
  [headers.values]
    Access-Control-Allow-Origin = "https://giscus.app"

[[plugins]]
  package = "netlify-plugin-cypress"

[[plugins]]
  package = "netlify-plugin-no-more-404"

  [plugins.inputs]
  # either "warn" or "error"
  on404 = "warn"
  cacheKey = "no-more-404-v2"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = ""

  [[plugins.inputs.audits]]
    path = "/blog/2020/markdown-capabilities-in-eleventy/"

  [plugins.inputs.thresholds]
    performance = 0.6
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    # pwa = 0.9

# [[edge_functions]]
# function = "eleventy-edge"
# path = "/*"
