[build]
  command = "npm run production"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "12"

[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
    # cache for one month
    cache-control = "public, max-age=2592000"