name: Lighthouse Audit
on:
  push:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 3 minutes
        uses: jakejarvis/wait-action@master
        with:
          time: '3m'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse and ensure performance budget
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://lukastrumm.com/
            https://lukastrumm.com/blog/2020/markdown-capabilities-in-eleventy/
            https://lukastrumm.com/projects
          budgetPath: .github/lighthouse/budget.json
          configPath: .github/lighthouse/lighthouserc.json
          temporaryPublicStorage: true
